#!/bin/bash
# Dieses Skript befindet sich in /usr/bin/ipv6-check

output_file='ipv6.l'

function ipv6-check() {
  [[ "$(wget -qO - nsx.de|tail -n 4|head -n 1)" != "$(tail -n 1 "${output_file}")" ]] &&  wget -qO - nsx.de|tail -n 4|head -n 1 >>"${output_file}"
  }
  
while true;
  do ipv6-check;
  sleep 1;
done
